In [2]:
import pandas as pd
import numpy as np

# scikit-learn utilities
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

# scikit-learn models
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LogisticRegression

In [151]:
lgb_table = pd.read_csv("../data/lgb_table_ids.csv")
lgb_pages = pd.read_csv("../data/lgb_pages_v2.csv")

In [158]:
lgb_pages_nodups = lgb_pages.drop_duplicates()

In [17]:
# lgb_table_nodups = lgb_table.loc[:, ['Title', 'Notes']].drop_duplicates()

In [159]:
lgb_merged = pd.merge(lgb_table, lgb_pages_nodups, how='inner', on='pageid')

In [97]:
# lgb_merged = pd.merge(lgb_table, lgb_pages, how='inner', left_on='Title', right_on='title')

In [162]:
lgb_merged.loc[lgb_merged.Notes == 'G.', 'Notes'] = 'G'

In [260]:
# relabel both Kray twins as B, not B & G
# Ronnie Kray describes himself as both homosexual and bisexual 
# according to his wiki entry
lgb_merged.loc[lgb_merged.title == 'Kray twins', 'Notes'] = 'B'

In [261]:
lgb_merged_nodups = lgb_merged.loc[:, ['Notes', 'title', 'pageid', 'url', 'summary', 'content']].drop_duplicates()

In [281]:
lgb_merged_nodups.reset_index(drop=True, inplace=True)

In [101]:
svm_clf = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()), 
                    ('svm', LinearSVC(loss='hinge'))])

In [282]:
X = lgb_merged_nodups['content']
y = lgb_merged_nodups['Notes']

In [283]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, 
                                                        train_size=0.75, test_size=0.25)
svm_clf.fit(X_train, y_train)
y_svm = svm_clf.predict(X_test)

In [284]:
print(classification_report(y_test, y_svm))

             precision    recall  f1-score   support

          B       1.00      0.03      0.07        86
          G       0.90      0.98      0.94       474
          L       0.76      0.94      0.84       161

avg / total       0.88      0.86      0.81       721



In [265]:
accuracy_score(y_test, y_svm)

0.86130374479889038

In [167]:
lgb_merged.Notes.describe()

count     2896
unique       3
top          G
freq      1892
Name: Notes, dtype: object

In [168]:
lgb_merged.groupby('Notes')['Name'].count()

Notes
B     342
G    1892
L     662
Name: Name, dtype: int64

In [239]:
lgb_merged.loc[:, ['Notes', 'pageid']].drop_duplicates().groupby('Notes')['pageid'].count()

Notes
B     340
G    1884
L     659
Name: pageid, dtype: int64

In [169]:
lgb_merged.shape

(2896, 11)

In [170]:
from sklearn.metrics import confusion_matrix

In [266]:
print(confusion_matrix(y_test, y_svm))

[[  3  42  41]
 [  0 466   8]
 [  0   9 152]]


In [267]:
lr_clf = Pipeline([('vect', CountVectorizer()),
                   ('tfidf', TfidfTransformer()), 
                   ('lr', LogisticRegression())])

In [268]:
lr_clf.fit(X_train, y_train)
y_lr = lr_clf.predict(X_test)

In [269]:
print(classification_report(y_test, y_lr))

             precision    recall  f1-score   support

          B       1.00      0.02      0.05        86
          G       0.89      0.99      0.93       474
          L       0.75      0.89      0.81       161

avg / total       0.87      0.85      0.80       721



In [270]:
accuracy_score(y_test, y_lr)

0.85020804438280162

In [271]:
print(confusion_matrix(y_test, y_lr))

[[  2  42  42]
 [  0 467   7]
 [  0  17 144]]


In [272]:
lgb_merged.iloc[y_test.index].loc[lgb_merged.Notes == 'B']

Name                            Title       Lifetime  \
1137    Devin K. Grayson                 Devin K. Grayson           b. ?   
953     Gustave Flaubert                 Gustave Flaubert      1821–1880   
822            Andy Dick                        Andy Dick        b. 1965   
1280         Aaron Henry                      Aaron Henry      1922–1977   
2596       Rebecca Sugar                    Rebecca Sugar        b. 1987   
2729        Yona Wallach                     Yona Wallach      1944–1985   
745            Tom Daley                        Tom Daley        b. 1994   
198    Tallulah Bankhead                Tallulah Bankhead      1902–1968   
437       Romaine Brooks                   Romaine Brooks      1874–1970   
2892      Aileen Wuornos                   Aileen Wuornos      1956–2002   
769           Ron Davies  Ron Davies (British politician)        b. 1946   
1757        Logan McCree                     Logan McCree        b. 1977   
2660            Tiberius                         Tiberius  42 BC – 37 AD   
2752        Ethel Waters                     Ethel Waters      1896–1977   
302      Kajsa Bergqvist                  Kajsa Bergqvist        b. 1976   
467       Horst Buchholz                   Horst Buchholz      1933–2003   
683    Patricia Cornwell                Patricia Cornwell        b. 1956   
434        Rupert Brooke                    Rupert Brooke      1887–1915   
213         Djuna Barnes                     Djuna Barnes      1892–1982   
1447               Kesha                            Kesha        b. 1987   
1072           Thea Gill                        Thea Gill        b. 1970   
1488        Oswalt Kolle                     Oswalt Kolle      1928–2010   
1035         Jeff Gannon                      Jeff Gannon        b. 1958   
2875    Evan Rachel Wood                 Evan Rachel Wood        b. 1987   
884       Isadora Duncan                   Isadora Duncan      1887–1927   
2044     Anthony Perkins                  Anthony Perkins      1932–1992   
1251   Sophie B. Hawkins                Sophie B. Hawkins        b. 1967   
1820     Freddie Mercury                  Freddie Mercury      1946–1991   
1456    Billie Jean King                 Billie Jean King        b. 1943   
2455          Judee Sill                       Judee Sill      1944–1979   
...                  ...                              ...            ...   
846            Dong Xian                        Dong Xian     c. 23–1 BC   
2475          Ricky Sinz                       Ricky Sinz        b. 1980   
2840         Mara Wilson                      Mara Wilson        b. 1987   
499        Dorothy Bussy                    Dorothy Bussy      1865–1960   
1463       Alfred Kinsey                    Alfred Kinsey      1894–1956   
1844           Sal Mineo                        Sal Mineo      1939–1976   
561         Jack Cassidy                     Jack Cassidy      1927–1976   
2026             Peaches               Peaches (musician)        b. 1968   
2808        Jane Wiedlin                     Jane Wiedlin        b. 1958   
1372         Mia Hundvin                      Mia Hundvin        b. 1977   
466      Kathleen Bryson                  Kathleen Bryson        b. 1968   
1626    Duke Ling of Wei                 Duke Ling of Wei     534–493 BC   
2794          Mike White        Mike White (scriptwriter)        b. 1970   
240           Alan Bates                       Alan Bates      1934–2003   
164                Babur                            Babur      1483–1530   
2445        Nerina Shute                     Nerina Shute      1908–2004   
646       Joanna E. Cole                   Joanna E. Cole        b. 1948   
181      Josephine Baker                  Josephine Baker      1906–1975   
1099    Alison Goldfrapp                 Alison Goldfrapp        b. 1966   
2730      Rebecca Walker                   Rebecca Walker        b. 1969   
250          Jaime Bayly                      Jaime Bayly        b. 

In [273]:
test_df = pd.DataFrame({'predicted': y_svm, 'actual': y_test}, index=y_test.index)

In [274]:
test_df_merged = test_df.merge(lgb_merged, left_index=True, right_index=True)

In [275]:
test_df_merged.loc[test_df_merged.actual == 'B']

actual predicted                Name                            Title  \
1137      B         L    Devin K. Grayson                 Devin K. Grayson   
953       B         G    Gustave Flaubert                 Gustave Flaubert   
822       B         G           Andy Dick                        Andy Dick   
1280      B         G         Aaron Henry                      Aaron Henry   
2596      B         L       Rebecca Sugar                    Rebecca Sugar   
2729      B         L        Yona Wallach                     Yona Wallach   
745       B         G           Tom Daley                        Tom Daley   
198       B         L   Tallulah Bankhead                Tallulah Bankhead   
437       B         L      Romaine Brooks                   Romaine Brooks   
2892      B         L      Aileen Wuornos                   Aileen Wuornos   
769       B         G          Ron Davies  Ron Davies (British politician)   
1757      B         G        Logan McCree                     Logan McCree   
2660      B         G            Tiberius                         Tiberius   
2752      B         L        Ethel Waters                     Ethel Waters   
302       B         L     Kajsa Bergqvist                  Kajsa Bergqvist   
467       B         G      Horst Buchholz                   Horst Buchholz   
683       B         L   Patricia Cornwell                Patricia Cornwell   
434       B         G       Rupert Brooke                    Rupert Brooke   
213       B         L        Djuna Barnes                     Djuna Barnes   
1447      B         L               Kesha                            Kesha   
1072      B         G           Thea Gill                        Thea Gill   
1488      B         G        Oswalt Kolle                     Oswalt Kolle   
1035      B         G         Jeff Gannon                      Jeff Gannon   
2875      B         L    Evan Rachel Wood                 Evan Rachel Wood   
884       B         L      Isadora Duncan                   Isadora Duncan   
2044      B         G     Anthony Perkins                  Anthony Perkins   
1251      B         L   Sophie B. Hawkins                Sophie B. Hawkins   
1820      B         G     Freddie Mercury                  Freddie Mercury   
1456      B         L    Billie Jean King                 Billie Jean King   
2455      B         B          Judee Sill                       Judee Sill   
...     ...       ...                 ...                              ...   
846       B         G           Dong Xian                        Dong Xian   
2475      B         G          Ricky Sinz                       Ricky Sinz   
2840      B         L         Mara Wilson                      Mara Wilson   
499       B         L       Dorothy Bussy                    Dorothy Bussy   
1463      B         G       Alfred Kinsey                    Alfred Kinsey   
1844      B         G           Sal Mineo                        Sal Mineo   
561       B         G        Jack Cassidy                     Jack Cassidy   
2026      B         L             Peaches               Peaches (musician)   
2808      B         L        Jane Wiedlin                     Jane Wiedlin   
1372      B         L         Mia Hundvin                      Mia Hundvin   
466       B         L     Kathleen Bryson                  Kathleen Bryson   
1626      B         G    Duke Ling of Wei                 Duke Ling of Wei   
2794      B         G          Mike White        Mike White (scriptwriter)   
240       B         G          Alan Bates                       Alan Bates   
164       B         G               Babur                            Babur   
2445      B         L        Nerina Shute                     Nerina Shute   
646       B         L      Joanna E. Cole                   Joanna E. Cole   
181       B         L     Josephine Baker                  Josephine Baker   
1099      B         L    Alison Goldfrapp                 Alison Goldfrapp   
2730      B         L      

In [276]:
test_df_merged.query("actual == 'B' & predicted == 'B'")

actual predicted        Name       Title   Lifetime Nationality  \
2455      B         B  Judee Sill  Judee Sill  1944–1979    American   
2384      B         B   Avy Scott   Avy Scott    b. 1981    American   
443       B         B  Erin Brown  Erin Brown    b. 1979     English   

                   Notable as Notes       pageid       title  \
2455    Singer and songwriter     B  1.84712e+06  Judee Sill   
2384                Porn star     B  1.87154e+06   Avy Scott   
443   Actor, model, filmmaker     B  6.20759e+06  Erin Brown   

                                           url  \
2455  https://en.wikipedia.org/wiki/Judee_Sill   
2384   https://en.wikipedia.org/wiki/Avy_Scott   
443   https://en.wikipedia.org/wiki/Erin_Brown   

                                                summary  \
2455  Judee Sill (born Judith Lynne Sill, October 7,...   
2384  Avy Scott (born in November 2, 1981) is the st...   
443   Erin Brown (born Erin DeWright; October 16, 19...   

                                                content  
2455  Judee Sill (born Judith Lynne Sill, October 7,...  
2384  Avy Scott (born in November 2, 1981) is the st...  
443   Erin Brown (born Erin DeWright; October 16, 19...

In [277]:
test_df_merged.query("actual == 'B' & predicted == 'G'")

actual predicted                               Name  \
953       B         G                   Gustave Flaubert   
822       B         G                          Andy Dick   
1280      B         G                        Aaron Henry   
745       B         G                          Tom Daley   
769       B         G                         Ron Davies   
1757      B         G                       Logan McCree   
2660      B         G                           Tiberius   
467       B         G                     Horst Buchholz   
434       B         G                      Rupert Brooke   
1072      B         G                          Thea Gill   
1488      B         G                       Oswalt Kolle   
1035      B         G                        Jeff Gannon   
2044      B         G                    Anthony Perkins   
1820      B         G                    Freddie Mercury   
2130      B         G                         James Rado   
2057      B         G            Prince Philipp of Hesse   
1105      B         G                  Witold Gombrowicz   
1136      B         G                           Jim Gray   
515       B         G                           Caligula   
1380      B         G                          Huo Guang   
260       B         G  William Lygon, 7th Earl Beauchamp   
1368      B         G                 Emperor Hui of Han   
807       B         G                Robert De Niro, Sr.   
1037      B         G               Emperor Gaozu of Han   
709       B         G                   Aleister Crowley   
108       B         G                       Louis Aragon   
2316      B         G                           Ola Salo   
293       B         G                     Taylor Bennett   
846       B         G                          Dong Xian   
2475      B         G                         Ricky Sinz   
1463      B         G                      Alfred Kinsey   
1844      B         G                          Sal Mineo   
561       B         G                       Jack Cassidy   
1626      B         G                   Duke Ling of Wei   
2794      B         G                         Mike White   
240       B         G                         Alan Bates   
164       B         G                              Babur   
250       B         G                        Jaime Bayly   
551       B         G                        Jim Carroll   
1634      B         G                        Ollie Locke   
2103      B         G                    Francis Poulenc   
1238      B         G                     Patrick Harvie   

                                  Title       Lifetime            Nationality  \
953                    Gustave Flaubert      1821–1880                 French   
822                           Andy Dick        b. 1965               American   
1280                        Aaron Henry      1922–1977               American   
745                           Tom Daley        b. 1994                British   
769     Ron Davies (British politician)        b. 1946                  Welsh   
1757                       Logan McCree        b. 1977                 German   
2660                           Tiberius  42 BC – 37 AD                  Roman   
467                      Horst Buchholz      1933–2003                 German   
434                       Rupert Brooke      1887–1915                English   
1072                          Thea Gill        b. 1970               Canadian   
1488                       Oswalt Kolle      1928–2010           German/Dutch   
1035                        Jeff Gannon        b. 1958               American   
2044                    Anthony Perkins      1932–1992               American   
1820                    Freddie Mercury      1946–1991                British   
2130                         James Rado        b. 1932               American   
2057            Prince Philipp of Hesse      1896–1980                 German   
1105                  Witold Gombrowicz      19

In [278]:
test_df_merged.query("actual == 'B' & predicted == 'L'")

actual predicted                Name                     Title  \
1137      B         L    Devin K. Grayson          Devin K. Grayson   
2596      B         L       Rebecca Sugar             Rebecca Sugar   
2729      B         L        Yona Wallach              Yona Wallach   
198       B         L   Tallulah Bankhead         Tallulah Bankhead   
437       B         L      Romaine Brooks            Romaine Brooks   
2892      B         L      Aileen Wuornos            Aileen Wuornos   
2752      B         L        Ethel Waters              Ethel Waters   
302       B         L     Kajsa Bergqvist           Kajsa Bergqvist   
683       B         L   Patricia Cornwell         Patricia Cornwell   
213       B         L        Djuna Barnes              Djuna Barnes   
1447      B         L               Kesha                     Kesha   
2875      B         L    Evan Rachel Wood          Evan Rachel Wood   
884       B         L      Isadora Duncan            Isadora Duncan   
1251      B         L   Sophie B. Hawkins         Sophie B. Hawkins   
1456      B         L    Billie Jean King          Billie Jean King   
1458      B         L       Florence King             Florence King   
682       B         L     Jessica Cornish           Jessica Cornish   
2827      B         L     Rachel Williams           Rachel Williams   
29        B         L     Patience Agbabi           Patience Agbabi   
276       B         L          Aphra Behn                Aphra Behn   
1814      B         L         Rosa Mendes               Rosa Mendes   
371       B         L       Lizzie Borden  Lizzie Borden (director)   
1596      B         L     Jasmine Lennard           Jasmine Lennard   
1244      B         L   Beatrice Hastings         Beatrice Hastings   
436       B         L       Louise Brooks             Louise Brooks   
2840      B         L         Mara Wilson               Mara Wilson   
499       B         L       Dorothy Bussy             Dorothy Bussy   
2026      B         L             Peaches        Peaches (musician)   
2808      B         L        Jane Wiedlin              Jane Wiedlin   
1372      B         L         Mia Hundvin               Mia Hundvin   
466       B         L     Kathleen Bryson           Kathleen Bryson   
2445      B         L        Nerina Shute              Nerina Shute   
646       B         L      Joanna E. Cole            Joanna E. Cole   
181       B         L     Josephine Baker           Josephine Baker   
1099      B         L    Alison Goldfrapp          Alison Goldfrapp   
2730      B         L      Rebecca Walker            Rebecca Walker   
2885      B         L         Kate Worley               Kate Worley   
2656      B         L        Bella Thorne              Bella Thorne   
1576      B         L      Violette Leduc            Violette Leduc   
1309      B         L  Patricia Highsmith        Patricia Highsmith   
444       B         L          Kate Brown                Kate Brown   

       Lifetime Nationality                                  Notable as Notes  \
1137       b. ?    American              Comic book writer and novelist     B   
2596    b. 1987    American  Animator, composer, director, show creator     B   
2729  1944–1985     Israeli                                        Poet     B   
198   1902–1968    American                                     Actress     B   
437   1874–1970    American                                     Painter     B   
2892  1956–2002    American                               Serial killer     B   
2752  1896–1977    American                    Jazz/pop musician, actor     B   
302     b. 1976     Swedish                                 High Jumper     B   
683     b. 1956    American                                      Author     B   
213   1892–1982    American                                      Writer     B   
1447    b. 1987    American                           Singer-songwriter     B   
2875    b. 1987    American                       

In [279]:
y_test

475     G
1465    G
2393    G
1614    G
1102    G
1265    G
1137    B
2268    G
953     B
1813    L
2790    G
2777    L
372     G
1773    L
822     B
785     G
502     G
242     G
335     G
843     G
960     L
1231    G
1280    B
2391    G
1791    L
1530    L
2015    G
1018    G
1765    G
1927    G
       ..
1238    B
1697    L
1885    L
283     L
845     G
1079    L
1492    L
1522    L
1953    G
787     G
600     G
2283    G
2866    L
2625    G
444     B
512     L
76      G
1756    G
653     G
526     G
2354    G
864     L
2609    G
861     G
1425    L
1098    L
1525    L
634     L
2523    L
1397    G
Name: Notes, Length: 721, dtype: object

## Notable as...

what if I tokenize this field and use it to create groups

ideal: filter stopwords, stem?, turn in to tf-idf matrix [nouns only?]

would be a good way to label t-SNE plot, mainly

people are often notable for more than one thing... could arbitrarily pick the first one

[that's hard too]

In [186]:
import gensim

In [188]:
notable = [gensim.utils.simple_preprocess(n) for n in lgb_merged['Notable as']]

In [206]:
len([True for n in notable if 'musician' in n or 'singer' in n])

352

In [204]:
len([True for n in notable if 'actor' in n or 'actress' in n])

421

In [201]:
len([True for n in notable if 'politician' in n])

343

In [202]:
len([True for n in notable if 'activist' in n])

171

In [224]:
len([True for n in notable if 'writer' in n or 'poet' in n or 'author' in n])

626

In [211]:
len([True for n in notable if 'model' in n])

29

In [213]:
len([True for n in notable if 'comedian' in n])

71

In [222]:
len([True for n in notable if 'academic' in n or 'scientist' in n])

18

In [221]:
len([True for n in notable if 'athlete' in n or 'skater' in n])

31

In [223]:
len([True for n in notable if 'artist' in n])

91

In [228]:
import nltk
stops = nltk.corpus.stopwords.words('english')

In [230]:
notable2 = [nn for n in notable for nn in n if nn not in stops]

In [232]:
from collections import Counter 
counter = Counter(notable2)

In [234]:
counter.most_common(n=20)

[('writer', 432),
 ('actor', 381),
 ('politician', 343),
 ('musician', 247),
 ('activist', 171),
 ('director', 137),
 ('singer', 111),
 ('author', 110),
 ('poet', 103),
 ('artist', 91),
 ('film', 91),
 ('journalist', 82),
 ('television', 80),
 ('rights', 79),
 ('rock', 79),
 ('composer', 78),
 ('lgbt', 77),
 ('playwright', 75),
 ('pop', 71),
 ('comedian', 71)]

In [236]:
counter.most_common()

[('writer', 432),
 ('actor', 381),
 ('politician', 343),
 ('musician', 247),
 ('activist', 171),
 ('director', 137),
 ('singer', 111),
 ('author', 110),
 ('poet', 103),
 ('artist', 91),
 ('film', 91),
 ('journalist', 82),
 ('television', 80),
 ('rights', 79),
 ('rock', 79),
 ('composer', 78),
 ('lgbt', 77),
 ('playwright', 75),
 ('pop', 71),
 ('comedian', 71),
 ('player', 60),
 ('producer', 59),
 ('screenwriter', 51),
 ('filmmaker', 51),
 ('designer', 49),
 ('classical', 49),
 ('personality', 45),
 ('songwriter', 44),
 ('actress', 41),
 ('tv', 34),
 ('gay', 33),
 ('fashion', 33),
 ('photographer', 32),
 ('presenter', 30),
 ('novelist', 29),
 ('model', 29),
 ('dancer', 28),
 ('porn', 26),
 ('radio', 25),
 ('painter', 23),
 ('first', 22),
 ('star', 22),
 ('historian', 21),
 ('show', 20),
 ('host', 20),
 ('choreographer', 19),
 ('skater', 19),
 ('critic', 18),
 ('performer', 18),
 ('reality', 18),
 ('olympic', 17),
 ('lawyer', 17),
 ('figure', 17),
 ('music', 16),
 ('killer', 16),
 ('jazz

## Nationality

In [251]:
lgb_merged.groupby('Nationality')['Name'].count().sort_values(ascending=False).head(20)

Nationality
American         1445
English           293
Canadian          241
German            105
British            92
Australian         86
French             70
Swedish            40
Scottish           29
Irish              26
Dutch              25
Italian            22
Norwegian          19
New Zealander      18
Russian            17
Mexican            15
Belgian            14
Finnish            12
South African      12
Spanish            12
Name: Name, dtype: int64